#!/bin/bash


# SPDX-License-Identifier: GPL-3.0-or-later

# DCSDCHK
# Dreamcast disc image utility that checks, converts and renames DCSDRIP dumps

# Copyright (C) 2024 Jon Blau

# This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.


# build : creates directories then compiles sub programs

mkdir -p 'db' 'gd' 'sp'

gcc read.c -o sp/read && echo -e "read \t \e[42m success \e[0m " || echo -e "read \t \e[41m failure \e[0m"
gcc write.c -o sp/write && echo -e "write \t \e[42m success \e[0m " || echo -e "write \t \e[41m failure \e[0m"
